// <auto-generated />
using System;
using FibertelData.Sources.BaseDeDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FibertelApiRest.Migrations
{
    [DbContext(typeof(FibertelDbContext))]
    partial class FibertelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.AdministradorTable", b =>
                {
                    b.Property<int>("idAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonoMovil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("idAdministrador");

                    b.ToTable("administradors", "Tienda");

                    b.HasData(
                        new
                        {
                            idAdministrador = 1,
                            email = "luis@fibertel.com",
                            estado = true,
                            nombres = "Luis Rosales Rosales",
                            password = "123456789",
                            telefonoMovil = "983234873"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.BannerTable", b =>
                {
                    b.Property<int>("idBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("enlace")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("idBanner");

                    b.ToTable("banners", "Tienda");

                    b.HasData(
                        new
                        {
                            idBanner = 1,
                            enlace = "http://localhost:4200/categoria/1",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/banners%2FBannerPrincipal.png?alt=media&token=67c05c02-3c7f-4542-b556-fb29f2aaa50e"
                        },
                        new
                        {
                            idBanner = 2,
                            enlace = "http://localhost:4200/categoria/8",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/banners%2FBannerLaptops.png?alt=media&token=63ee6e5d-97bf-4456-b167-5593d6d5b5a9"
                        },
                        new
                        {
                            idBanner = 3,
                            enlace = "http://localhost:4200/marca/1",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/banners%2FBannerCelulares.png?alt=media&token=3710d7bc-3821-4402-b4be-31dd4a34a806"
                        },
                        new
                        {
                            idBanner = 4,
                            enlace = "http://localhost:4200/producto/1",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/banners%2FBannerLaptops.png?alt=media&token=63ee6e5d-97bf-4456-b167-5593d6d5b5a9"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.CategoriaTable", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoriaNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("idCategoria");

                    b.ToTable("categorias", "Tienda");

                    b.HasData(
                        new
                        {
                            idCategoria = 1,
                            categoriaNombre = "Monitores",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 2,
                            categoriaNombre = "Routers",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 3,
                            categoriaNombre = "Accesorios",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 4,
                            categoriaNombre = "Audio",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 5,
                            categoriaNombre = "Cables",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 6,
                            categoriaNombre = "Oficina",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 7,
                            categoriaNombre = "Celulares",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2FCategoria.png?alt=media&token=afb9e781-18e6-4152-b38d-29e009fe788a"
                        },
                        new
                        {
                            idCategoria = 8,
                            categoriaNombre = "Laptops",
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/categorias%2Fcategory.png?alt=media&token=b47cd212-75ee-43bc-a0c3-de585b338b1e"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ClienteTable", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("direccionFiscal")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonoMovil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("idCliente");

                    b.ToTable("clientes", "Movimientos");

                    b.HasData(
                        new
                        {
                            idCliente = 1,
                            email = "maicolrosas@gmail.com",
                            numeroDocumento = "23171287",
                            razonSocial = "Maicol Linares Rosales",
                            telefonoMovil = "902393648",
                            tipoDocumento = "DNI"
                        },
                        new
                        {
                            idCliente = 2,
                            direccionFiscal = "Junin, Huancayo, Huancayo Jr Loreto 190",
                            email = "anaflores@gmail.com",
                            numeroDocumento = "201203944584544",
                            razonSocial = "Ana Rosas Rosas",
                            telefonoMovil = "902383983",
                            tipoDocumento = "RUC"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ComprobanteTable", b =>
                {
                    b.Property<int>("idComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<int>("idPedido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipoComprobante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("idComprobante");

                    b.HasIndex("idPedido")
                        .IsUnique();

                    b.ToTable("comprobantes", "Movimientos");

                    b.HasData(
                        new
                        {
                            idComprobante = 1,
                            fechaEmision = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idPedido = 1,
                            tipoComprobante = "Boleta"
                        },
                        new
                        {
                            idComprobante = 2,
                            fechaEmision = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idPedido = 2,
                            tipoComprobante = "Factura"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.DetallePedidoTable", b =>
                {
                    b.Property<int>("idDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idPedido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProducto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("precioDescuento")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("precioUnitario")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("subTotal")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("idDetallePedido");

                    b.HasIndex("idPedido");

                    b.HasIndex("idProducto");

                    b.ToTable("detallePedidos", "Movimientos");

                    b.HasData(
                        new
                        {
                            idDetallePedido = 1,
                            cantidad = 1,
                            idPedido = 1,
                            idProducto = 3,
                            precioDescuento = 2000.90m,
                            precioUnitario = 2300.90m,
                            subTotal = 2000.90m
                        },
                        new
                        {
                            idDetallePedido = 2,
                            cantidad = 5,
                            idPedido = 2,
                            idProducto = 12,
                            precioDescuento = 2000.90m,
                            precioUnitario = 2300.90m,
                            subTotal = 2000.90m
                        },
                        new
                        {
                            idDetallePedido = 3,
                            cantidad = 2,
                            idPedido = 2,
                            idProducto = 7,
                            precioDescuento = 2000.90m,
                            precioUnitario = 2300.90m,
                            subTotal = 2000.90m
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.EnvioTable", b =>
                {
                    b.Property<int>("idEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("codigoPostal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("distrito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("fechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("fechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("idPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("nDomicilio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("responsableEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("idEnvio");

                    b.HasIndex("idPersonal");

                    b.ToTable("envios", "Movimientos");

                    b.HasData(
                        new
                        {
                            idEnvio = 1,
                            calle = "Av Rosales",
                            codigoPostal = "202025",
                            distrito = "Lima",
                            fechaEnvio = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idPersonal = 1,
                            localidad = "Lima Lima Lima",
                            nDomicilio = "230",
                            provincia = "Lima",
                            region = "Lima",
                            responsableEntrega = "Felipe Sarmiento - 72342312"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.MarcaTable", b =>
                {
                    b.Property<int>("idMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("marcaNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("idMarca");

                    b.ToTable("marcas", "Tienda");

                    b.HasData(
                        new
                        {
                            idMarca = 1,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Epson"
                        },
                        new
                        {
                            idMarca = 2,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Asus"
                        },
                        new
                        {
                            idMarca = 3,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Sony"
                        },
                        new
                        {
                            idMarca = 4,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Huawei"
                        },
                        new
                        {
                            idMarca = 5,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Lenovo"
                        },
                        new
                        {
                            idMarca = 6,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2Fjbl.png?alt=media&token=f5ac8d03-ca68-498c-9a7e-b38a1ead6314",
                            marcaNombre = "Jbl"
                        },
                        new
                        {
                            idMarca = 7,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2Fsamsung.png?alt=media&token=3cd77c5b-6e89-4ccb-9c28-6fc9f7cbae2e",
                            marcaNombre = "Samsung"
                        },
                        new
                        {
                            idMarca = 8,
                            estado = true,
                            imagen = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/marcas%2FMarca.png?alt=media&token=bd0aa8ae-7e2a-4370-b0d9-7c690f001881",
                            marcaNombre = "Generico"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("fechaCancelado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("idCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("idEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("idPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("idRecojo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("total")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("idPedido");

                    b.HasIndex("idCliente")
                        .IsUnique();

                    b.HasIndex("idEnvio")
                        .IsUnique();

                    b.HasIndex("idPersonal");

                    b.HasIndex("idRecojo")
                        .IsUnique();

                    b.ToTable("pedidos", "Movimientos");

                    b.HasData(
                        new
                        {
                            idPedido = 1,
                            estado = "Enviado",
                            fechaPedido = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idCliente = 1,
                            idEnvio = 1,
                            idPersonal = 1,
                            tipoPedido = "Envio a Domicilio",
                            total = 5010.90m
                        },
                        new
                        {
                            idPedido = 2,
                            estado = "Entregado",
                            fechaPedido = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idCliente = 2,
                            idPersonal = 1,
                            idRecojo = 1,
                            tipoPedido = "Recojo en Tienda",
                            total = 5010.90m
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.PersonalTable", b =>
                {
                    b.Property<int>("idPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("contacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("finOperacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("inicioOperacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("idPersonal");

                    b.ToTable("personals", "Movimientos");

                    b.HasData(
                        new
                        {
                            idPersonal = 1,
                            apellidos = "Merino Zalasar",
                            contacto = "982332873",
                            inicioOperacion = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombres = "Andy",
                            numeroDocumento = "73123465",
                            rol = "Responsable de Envio"
                        },
                        new
                        {
                            idPersonal = 2,
                            apellidos = "Merino Rosas",
                            contacto = "982332873",
                            inicioOperacion = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombres = "Luis Felipe",
                            numeroDocumento = "70123465",
                            rol = "Responsable de Envio"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ProductoTable", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idMarca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen01")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen02")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen03")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen04")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("precio")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("precioOferta")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("productoNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("idProducto");

                    b.HasIndex("idCategoria");

                    b.HasIndex("idMarca");

                    b.ToTable("productos", "Tienda");

                    b.HasData(
                        new
                        {
                            idProducto = 1,
                            cantidad = 25,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 1,
                            idMarca = 1,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 201.90m,
                            precioOferta = 180.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 2,
                            cantidad = 10,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 2,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 7101.90m,
                            precioOferta = 2000.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 3,
                            cantidad = 25,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 3,
                            idMarca = 3,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 601.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 4,
                            cantidad = 21,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 4,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 901.90m,
                            precioOferta = 880.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 5,
                            cantidad = 46,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 5,
                            idMarca = 5,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 201.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 6,
                            cantidad = 67,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 6,
                            idMarca = 6,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            precio = 1201.90m,
                            precioOferta = 980.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 7,
                            cantidad = 87,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 7,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 3201.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 8,
                            cantidad = 45,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 8,
                            idMarca = 8,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            precio = 7801.90m,
                            precioOferta = 5680.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 9,
                            cantidad = 23,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 1,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 1201.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 10,
                            cantidad = 12,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 2,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 3201.90m,
                            precioOferta = 2980.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 11,
                            cantidad = 11,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 3,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 5201.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 12,
                            cantidad = 45,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            precio = 6201.90m,
                            precioOferta = 4580.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 13,
                            cantidad = 67,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 5,
                            idMarca = 5,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 8301.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 14,
                            cantidad = 98,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 6,
                            idMarca = 6,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 3201.90m,
                            precioOferta = 2580.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 15,
                            cantidad = 77,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 7,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 7901.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 16,
                            cantidad = 54,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 8,
                            idMarca = 8,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 41.90m,
                            precioOferta = 30.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 17,
                            cantidad = 65,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 1,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 201.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 18,
                            cantidad = 32,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 2,
                            idMarca = 2,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 9001.90m,
                            precioOferta = 8580.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        },
                        new
                        {
                            idProducto = 19,
                            cantidad = 14,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 3,
                            idMarca = 3,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto32.png?alt=media&token=066fef94-966c-436a-b888-5e03447a9ad8",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2FProducto31.png?alt=media&token=e9913773-a042-4aa9-baff-45715bf47d20",
                            precio = 4201.90m,
                            productoNombre = "LAPTOP HP 15-FB2002LA AMD RYZEN 5 8645HS 8GB 512GB SSD RTX 3050 15.6\""
                        },
                        new
                        {
                            idProducto = 20,
                            cantidad = 25,
                            detalle = "Procesador: AMD Ryzen Tamaño de la pantalla: 15 Disco duro: 512GB SSD Disco duro sólido: 512GB SSD Núcleos del procesador: Quad core Memoria total: 16GB Velocidad del procesador: 2.8 GHz Velocidad máxima del procesador: 4.3 GHz Modelo del procesador: AMD Ryzen 5 7520U Generación del procesador: Serie 7000 Memoria RAM: 16GB RAM expandible: No Tarjeta de video: No Aplica Capacidad de la tarjeta de video: No aplica Tipo de pantalla: LCD Marca: Lenovo Modelo: 82VG00GWLM Tipo: Notebook Nombre comercial: IdeaPad 1 15AMN7 Hecho en: China Garantía del proveedor: 1 Año Condición del producto: Nuevo",
                            estado = true,
                            idCategoria = 4,
                            idMarca = 4,
                            imagen01 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct01.png?alt=media&token=854dd6ba-432a-4283-87c7-dd5e695e4831",
                            imagen02 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct22.png?alt=media&token=1b3f7141-c5eb-4120-a3b9-01f4cc12ed8b",
                            imagen03 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct23.png?alt=media&token=a3397a80-18ef-4419-b9e4-8d3f62836629",
                            imagen04 = "https://firebasestorage.googleapis.com/v0/b/image-upload-458ca.appspot.com/o/productos%2Fproduct24.png?alt=media&token=1ea70b03-b2a0-4638-9524-e44574dffd01",
                            precio = 201.90m,
                            precioOferta = 180.90m,
                            productoNombre = "MONITOR CAIXUN 22' C22X3F PLANA FULL HD PANEL IPS 75HZ 14MS"
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.RecojoTable", b =>
                {
                    b.Property<int>("idRecojo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("fechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("fechaListo")
                        .HasColumnType("TEXT");

                    b.Property<string>("responsableEntrega")
                        .HasColumnType("TEXT");

                    b.HasKey("idRecojo");

                    b.ToTable("recojos", "Movimientos");

                    b.HasData(
                        new
                        {
                            idRecojo = 1,
                            fechaEntrega = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaListo = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ComprobanteTable", b =>
                {
                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", null)
                        .WithOne()
                        .HasForeignKey("FibertelData.Sources.BaseDeDatos.Tables.ComprobanteTable", "idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.DetallePedidoTable", b =>
                {
                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.ProductoTable", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.EnvioTable", b =>
                {
                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.PersonalTable", null)
                        .WithMany()
                        .HasForeignKey("idPersonal");
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", b =>
                {
                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.ClienteTable", "Cliente")
                        .WithOne("Pedido")
                        .HasForeignKey("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", "idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.EnvioTable", "Envio")
                        .WithOne("Pedido")
                        .HasForeignKey("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", "idEnvio");

                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.PersonalTable", null)
                        .WithMany()
                        .HasForeignKey("idPersonal");

                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.RecojoTable", "Recojo")
                        .WithOne("Pedido")
                        .HasForeignKey("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", "idRecojo");

                    b.Navigation("Cliente");

                    b.Navigation("Envio");

                    b.Navigation("Recojo");
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ProductoTable", b =>
                {
                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.CategoriaTable", null)
                        .WithMany()
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FibertelData.Sources.BaseDeDatos.Tables.MarcaTable", null)
                        .WithMany()
                        .HasForeignKey("idMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ClienteTable", b =>
                {
                    b.Navigation("Pedido")
                        .IsRequired();
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.EnvioTable", b =>
                {
                    b.Navigation("Pedido")
                        .IsRequired();
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.PedidoTable", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.ProductoTable", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("FibertelData.Sources.BaseDeDatos.Tables.RecojoTable", b =>
                {
                    b.Navigation("Pedido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
